# Use the official Nginx base image
FROM nginx:latest

# Copy the application files to the appropriate directory in the container
COPY ./index.html /usr/share/nginx/html

# Expose the port on which the web application will run
EXPOSE 80
